name: Pytest Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest with HTML report
      run: |
        pytest -v --html=report.html --self-contained-html

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html
